import { Inter } from "next/font/google";
import "./globals.css";
import DashboardContextProvider from "@/contexts/DashboardContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DashboardContextProvider>
        <body className={`${inter.className} h-full bg-white`}>{children}</body>
      </DashboardContextProvider>
    </html>
  );
}
